[workspace]
members = [
    "crates/utils",
    "crates/image",
    "crates/math"  # 共享代码
]

resolver = "2"  # 统一依赖版本


# 所有成员包共享的构建配置
[profile.dev]
opt-level = 1  # 开发模式优化级别

[profile.release]
lto = true     # 发布模式启用链接时优化